-- V11: Fix user password hashes with correct bcrypt format
-- These hashes are generated by Spring Security's BCryptPasswordEncoder (cost factor 10)
-- Passwords:
--   admin123 → admin user
--   operator123 → ahmed.operator and fatima.operator
--   test123 → manager.report

DO $$
BEGIN
    -- Update admin password hash
    UPDATE users 
    SET password_hash = '$2a$10$ITSy11J3mCW72hY0iXwe0eTFXu1CN/M1VjV1u6.DB2CwZpwzYVD8G'
    WHERE username = 'admin';
    
    -- Update ahmed.operator password hash
    UPDATE users 
    SET password_hash = '$2a$10$q9KzDB.YNhO00XnIhkGBqORTN0k0U/xa8M9oxzXiRmeUcDZSedc/2'
    WHERE username = 'ahmed.operator';
    
    -- Update fatima.operator password hash
    UPDATE users 
    SET password_hash = '$2a$10$q9KzDB.YNhO00XnIhkGBqORTN0k0U/xa8M9oxzXiRmeUcDZSedc/2'
    WHERE username = 'fatima.operator';
    
    -- Update manager.report password hash
    UPDATE users 
    SET password_hash = '$2a$10$kpgSIH9TQ01TWz40DPRERukvzHrC3Eo/Oql5NlePJw8Zi2/TUuvVO'
    WHERE username = 'manager.report';
    
    RAISE NOTICE 'User passwords updated with correct bcrypt hashes';
END $$;
